//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_CHIEN_DICH_MARKETING
    {
        public int ID { get; set; }
        public int ID_CHIEN_DICH { get; set; }
        public string MA_KHACH_HANG { get; set; }
    
        public virtual DM_LIST_CHIEN_DICH_MARKETING DM_LIST_CHIEN_DICH_MARKETING { get; set; }
        public virtual KH KH { get; set; }
    }
}
